# Generated by Django 5.0.11 on 2025-04-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('housing', 'Housing'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('education', 'Education'), ('other', 'Other')], max_length=20)),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
