# Generated by Django 5.0.11 on 2025-04-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
