# Generated by Django 5.0.11 on 2025-04-19 22:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('C2B', 'Customer to Business'), ('B2C', 'Business to Customer'), ('B2B', 'Business to Business')], max_length=10)),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone_number', models.CharField(max_length=15)),
                ('account_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_description', models.TextField(blank=True, null=True)),
                ('organization_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
