TRANSACTION_CATEGORIES = (
        ('food', 'Food'),
        ('transport', 'Transport'),
        ('housing', 'Housing'),
        ('entertainment', 'Entertainment'),
        ('health', 'Health'),
        ('education', 'Education'),
        ('other', 'Other'),
        ('savings', 'Savings'),
        ('investments', 'Investments'),
        ('utilities', 'Utilities'),
        ('clothing', 'Clothing'),
        ('gifts', 'Gifts'),
        ('travel', 'Travel'),
        ('groceries', 'Groceries'),
        ('subscriptions', 'Subscriptions'),
        ('bills', 'Bills'),
        ('miscellaneous', 'Miscellaneous'),
        ('debt_repayment', 'Debt Repayment'),
        ('insurance', 'Insurance'),
        ('charity', 'Charity'),
        ('home_improvement', 'Home Improvement'),
        ('furniture', 'Furniture'),
        ('electronics', 'Electronics'),
        ('toys', 'Toys'),
        ('sports', 'Sports'),
        ('hobbies', 'Hobbies'),
        ('pets', 'Pets'),
        ('vacation', 'Vacation'),
        ('events', 'Events'),
        ('personal_care', 'Personal Care'),
        ('transportation', 'Transportation'),
        ('home_services', 'Home Services'),
        ('legal', 'Legal'),
        ('professional_services', 'Professional Services'),
        ('business_expenses', 'Business Expenses'),
        ('marketing', 'Marketing'),
        ('software', 'Software'),
        ('website', 'Website'),
        ('advertising', 'Advertising'),
        ('consulting', 'Consulting'),
        ('training', 'Training'),
        ('education_tuition', 'Education Tuition'),
        ('childcare', 'Childcare'),
        ('eldercare', 'Eldercare'),
        ('medical', 'Medical'),
        ('dental', 'Dental'),
        ('vision', 'Vision'),
        ('mental_health', 'Mental Health'),
        ('wellness', 'Wellness'),
        ('fitness', 'Fitness'),
        ('gym_membership', 'Gym Membership'),
        ('sports_leagues', 'Sports Leagues'),
        ('outdoor_activities', 'Outdoor Activities'),
        ('cultural_events', 'Cultural Events'),
        ('performing_arts', 'Performing Arts'),
        ('music', 'Music'),
        ('movies', 'Movies'),
        ('books', 'Books'),
        ('games', 'Games'),
        ('crafts', 'Crafts'),
        ('gardening', 'Gardening'),
        ('home_decor', 'Home Decor'),
        ('home_maintenance', 'Home Maintenance'),
        ('home_security', 'Home Security'),
        ('home_improvement_tools', 'Home Improvement Tools'),
        ('home_appliances', 'Home Appliances'),
        ('kitchenware', 'Kitchenware'),
        ('cleaning_supplies', 'Cleaning Supplies'),
        ('laundry', 'Laundry'),
        ('yard_work', 'Yard Work'),
        ('pest_control', 'Pest Control'),
        ('seasonal_decorations', 'Seasonal Decorations'),
        ('holiday_expenses', 'Holiday Expenses'),
        ('gifts_for_others', 'Gifts for Others'),
        ('donations', 'Donations'),
        ('charitable_contributions', 'Charitable Contributions'),
        
    )
    